//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormView.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IViewAndUpdateServices")]
    public interface IViewAndUpdateServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewName", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewNameResponse")]
        string viewName(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewName", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewNameResponse")]
        System.Threading.Tasks.Task<string> viewNameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewEmail", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewEmailResponse")]
        string viewEmail(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewEmail", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewEmailResponse")]
        System.Threading.Tasks.Task<string> viewEmailAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewPassword", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewPasswordResponse")]
        string viewPassword(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewPassword", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewPasswordResponse")]
        System.Threading.Tasks.Task<string> viewPasswordAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewUserName", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewUserNameResponse")]
        string viewUserName(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewUserName", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewUserNameResponse")]
        System.Threading.Tasks.Task<string> viewUserNameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewMobileNumber", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewMobileNumberResponse")]
        string viewMobileNumber(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewMobileNumber", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewMobileNumberResponse")]
        System.Threading.Tasks.Task<string> viewMobileNumberAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewAddress", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewAddressResponse")]
        string viewAddress(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewAddress", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewAddressResponse")]
        System.Threading.Tasks.Task<string> viewAddressAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewCreditNumber", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewCreditNumberResponse")]
        string viewCreditNumber(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewCreditNumber", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewCreditNumberResponse")]
        System.Threading.Tasks.Task<string> viewCreditNumberAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewCreditPassword", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewCreditPasswordResponse")]
        string viewCreditPassword(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewAndUpdateServices/viewCreditPassword", ReplyAction="http://tempuri.org/IViewAndUpdateServices/viewCreditPasswordResponse")]
        System.Threading.Tasks.Task<string> viewCreditPasswordAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IViewAndUpdateServicesChannel : WebFormView.ServiceReference1.IViewAndUpdateServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewAndUpdateServicesClient : System.ServiceModel.ClientBase<WebFormView.ServiceReference1.IViewAndUpdateServices>, WebFormView.ServiceReference1.IViewAndUpdateServices {
        
        public ViewAndUpdateServicesClient() {
        }
        
        public ViewAndUpdateServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViewAndUpdateServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewAndUpdateServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewAndUpdateServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string viewName(int id) {
            return base.Channel.viewName(id);
        }
        
        public System.Threading.Tasks.Task<string> viewNameAsync(int id) {
            return base.Channel.viewNameAsync(id);
        }
        
        public string viewEmail(int id) {
            return base.Channel.viewEmail(id);
        }
        
        public System.Threading.Tasks.Task<string> viewEmailAsync(int id) {
            return base.Channel.viewEmailAsync(id);
        }
        
        public string viewPassword(int id) {
            return base.Channel.viewPassword(id);
        }
        
        public System.Threading.Tasks.Task<string> viewPasswordAsync(int id) {
            return base.Channel.viewPasswordAsync(id);
        }
        
        public string viewUserName(int id) {
            return base.Channel.viewUserName(id);
        }
        
        public System.Threading.Tasks.Task<string> viewUserNameAsync(int id) {
            return base.Channel.viewUserNameAsync(id);
        }
        
        public string viewMobileNumber(int id) {
            return base.Channel.viewMobileNumber(id);
        }
        
        public System.Threading.Tasks.Task<string> viewMobileNumberAsync(int id) {
            return base.Channel.viewMobileNumberAsync(id);
        }
        
        public string viewAddress(int id) {
            return base.Channel.viewAddress(id);
        }
        
        public System.Threading.Tasks.Task<string> viewAddressAsync(int id) {
            return base.Channel.viewAddressAsync(id);
        }
        
        public string viewCreditNumber(int id) {
            return base.Channel.viewCreditNumber(id);
        }
        
        public System.Threading.Tasks.Task<string> viewCreditNumberAsync(int id) {
            return base.Channel.viewCreditNumberAsync(id);
        }
        
        public string viewCreditPassword(int id) {
            return base.Channel.viewCreditPassword(id);
        }
        
        public System.Threading.Tasks.Task<string> viewCreditPasswordAsync(int id) {
            return base.Channel.viewCreditPasswordAsync(id);
        }
    }
}
